### ISSUE TITLE
Bank Simulator With Interest Returns

### ISSUE THREAD

**Issue by GitBolt** [Solana-Workshops/.contributing#3]
Link: https://github.com/GitBolt/solana-bank-workshop

I'm adding it to SolPg right now. In the meantime, you can review this one as well!

This is a simple bank simulator workshop, which uses Clockwork to automate interest returns and update user's balance every 10 seconds at the rate of 5% return every minute. 

Users can:
- Open Accounts (Multiple Bank Accounts Allowed)
- Deposit Balance
- Withdraw Balance
- See their balance going up automatically because of interest
- Delete their accounts

Since this is a simulation. The interest returns are lot, because we obviously wouldn't want someone to wait for a year to see 5% increment in their initial amount like real world haha

**Comment by GitBolt** [comment]
@buffalojoec you can review this one as well! also close the previous expense tracker one.
i've been waiting for acheron to review the tutorial, but seems like he is too busy, its been 3 weeks now

**Comment by buffalojoec** [comment]
Hey there, finally got around to reviewing this. Here's my feedback:
- In the README, you've got CRON and interest explained in the constants in section 1.1 but your title for 1.2 says "Interest and Seeds". Interest belongs in 1.1.
- You should explain a little bit more that Anchor makes these modules available to you at compile-time: `crate::accounts` and `crate::instructions`. Not many people (myself included) even know this is a thing.

```rust
// Clockwork Target Instruction
let target_ix = Instruction {
     program_id: ID,
     accounts: crate::accounts::AddInterest {
          bank_account: bank_account.key(),
          thread: thread.key(),
           thread_authority: thread_authority.key(),
     }.to_account_metas(Some(true)),
     data: crate::instruction::AddInterest {
           _thread_id: thread_id.clone(),
     }.data(),
 };
```

- This configuration seems kind of weird. Why not use `env()` for both Anchor provider calls, and why not pass `provider` into `ClockworkProvider` instead of `program.provider`?

```typescript
anchor.setProvider(anchor.AnchorProvider.env());
const provider = anchor.AnchorProvider.local();

const program = anchor.workspace.Etracker as Program<Bank>;
const wallet = provider.wallet as anchor.Wallet;

const clockworkProvider = ClockworkProvider.fromAnchorProvider(
  program.provider as AnchorProvider
);
```

- You're using two different Anchor versions in your client-side tests, and they didn't work out of the box for me.

```json
"dependencies": {
    "@clockwork-xyz/sdk": "^0.3.3",
    "@coral-xyz/anchor": "^0.27.0",
    "@project-serum/anchor": "^0.26.0"
},
```
```typescript
import { ClockworkProvider } from "@clockwork-xyz/sdk";
import * as anchor from "@project-serum/anchor";
import { Program } from "@project-serum/anchor";
import { Bank } from "../target/types/bank";
import { AnchorProvider } from "@coral-xyz/anchor";
```

- You don't have any details in your README about cloning the Clockwork program down to the local validator. In fact, you don't even have the configurations necessary to do it in your Anchor.toml. You need this:

```toml
[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "CLoCKyJ6DXBJqqu2VWx9RLbgnwwR6BMHHuyasVmfMzBh"
```

- Your naming conventions for the program are different across the various configuration files. You are calling it "program" in `Cargo.toml`, but you call it "bank" in other areas like `Anchor.toml`. These should all be the same.

- In the time since you first submitted this project, there's been a new Solana release (`1.16.10`), which has caused issues with Anchor's dependency tree. Please upgrade to Anchor v0.28.


Please address all above feedback, upgrade to Anchor v0.28, and fix the tests so they run for anyone who clones the repo.

Here's what I see when I run the tests:
<img width="1134" alt="Screenshot 2023-06-12 at 2 57 02 PM" src="https://github.com/Solana-Workshops/.contributing/assets/67205063/a5e08194-6771-4efb-8c21-32a2d7ab8102">

**Comment by GitBolt** [comment]
hey, appreciate it! yeah clearly i missed certain stuff. i used solpg to code it, so the proper local setup was missed as well. fixing them right now.

about versions. right now clockwork does not support solana v1.16.0 (https://github.com/clockwork-xyz/clockwork/releases)
so we can't use it right now, and hence, anchor v0.28 won't be required either. I'll fix dependency versions so that it works out of the box for Solana v1.14.16 or v1.14.17

**Comment by GitBolt** [comment]
Hey @buffalojoec. Can you check now? I've added detailed instruction of running it locally at the end of the Readme. Also, we don't need to clone the clockwork test validator right? The CLI tool has everything for us and works out of the box

**Comment by buffalojoec** [comment]
Thanks for addressing my feedback!

Couple more requests, then we should be good to go:
- Can we match Anchor versions for program & clients? In both clients you're using `0.26` but the program uses `0.27`
- Remove unused import in `lib.rs`: `native_token::LAMPORTS_PER_SOL`
- Put the "How to Build & Run" section of the README up top

**Comment by GitBolt** [comment]
Fixed! Here is the SolPg tutorial PR - https://github.com/solana-playground/solana-playground/pull/137

**Comment by buffalojoec** [comment]
Here's the new repo for ya https://github.com/Solana-Workshops/Bank-Simulator

**Comment by buffalojoec** [comment]
Thank you!
